### ISSUE TITLE
User stories & features

### ISSUE THREAD

**Issue by dhawk19** [dhawk19/SWE_Project-3#3]
Write one user story for each type of users that will use your software. Please refer to the lectures notes for a format of user stories. Write features of your software that are derived from product vision. Write features of your software that are derived from user stories.

**Comment by almightysnipes** [comment]
[features.txt](https://github.com/dhawk19/SWE_Project-3/files/10160523/features.txt)
[userstories.txt](https://github.com/dhawk19/SWE_Project-3/files/10160525/userstories.txt)
Features and user stories are completed. Waiting on your approval.

**Comment by dhawk19** [comment]
Issue approved.

**Comment by Daylinn** [comment]
Committed
